language: android
sudo: true
android:
  components:
    - tools
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "lldb;3.1"
before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
script:
  - ./gradlew clean check --profile
  - ./gradlew dependencyUpdates